### ISSUE TITLE
micromatch

### ISSUE THREAD

**Issue by jonschlinkert** [vweevers/level-glob#1]
hey I noticed you're using micromatch and seems like there is a bug (I think) [mentioned here](https://github.com/vweevers/level-glob/blob/master/index.js#L142). I pushed up a bunch of updates to micromatch this week if you want to try running the latest. 

If you do have any issues with the latest version, it would be great if you create an issue. just having use cases helps. (thanks btw)

**Comment by vweevers** [comment]
I've opened an issue for the negation stuff: #2. Thanks for bringing this to my attention, and for micromatch itself of course.

**Comment by jonschlinkert** [comment]
:+1: thanks for creating the issue
